<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>FlowTracker2Converter</AssemblyName>
    <RootNamespace>FlowTracker2Converter</RootNamespace>
    <ApplicationIcon>TimeSeries.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>..\External\ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\External\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SonTek.StandaloneDataParser">
      <HintPath>..\External\SonTek.StandaloneDataParser.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="6.2.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="log4net.config" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\External\SonTek.StandaloneDataParser.License.rtf">
      <Link>SonTek.StandaloneDataParser.License.rtf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnitConversion\UnitConversion.csproj" />
  </ItemGroup>
</Project>
